name: delivery
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  easy_localization: ^3.0.2
  flutter_bloc: ^8.1.3
  go_router: ^14.1.4
  flutter_screenutil: ^5.8.4
  flutter_native_splash: ^2.3.1
  dio: ^5.7.0
  equatable: ^2.0.5
  get_it: ^7.6.0
  injectable: ^2.1.2
  json_annotation: ^4.8.1
  flutter_tabler_icons: ^1.2.0
  flutter_secure_storage: ^9.2.2
  cached_network_image: ^3.3.1
  dotted_border: ^2.1.0
  photo_view: ^0.14.0
  flutter_datetime_picker_plus: ^2.1.0
  file_picker: ^8.0.6
  image_fade: ^0.6.2
  smooth_page_indicator: ^1.1.0
  image_cropper: ^4.0.1
  flutter_launcher_icons: ^0.13.1
  pinch_zoom: ^2.0.0
  permission_handler: ^10.4.5
  path_provider: ^2.1.2
  external_path: ^1.0.3
  keyboard_visibility_pro: ^0.0.1
  timeago: ^3.7.0
  step_progress_indicator: ^1.0.2
  flutter_svg: ^2.0.9
  bloc: ^8.1.4
  image_picker: ^1.1.2
  pretty_dio_logger: ^1.3.1
  fluent_ui: ^4.8.7
  dropdown_search: ^5.0.6
  search_choices: ^2.2.7
  spinner_dropdown: ^1.0.0
  snapping_sheet_2:
  easy_date_formatter:
  calendar_date_picker2: ^1.1.5
  oktoast: ^3.4.0
  firebase_core: ^3.6.0
  firebase_database: ^11.1.4
  firebase_messaging: ^15.1.3
  glowy_borders: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/png/
    - assets/fonts/
